### ISSUE TITLE
Implement profile screen

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/gobarber-mobile#10]
## Feature Description 

Implement a profile screen to update user info such as name, email, password, and avatar. Refer to the following layout

![image](https://user-images.githubusercontent.com/48022589/107501393-16564e80-6b76-11eb-836a-fcd4bb14dd5b.png)

## Tasks 

 - [x] Show base form 
 - [x] Show avatar image
 - [x] Implement image picker for avatar
 - [x] Implement `useUpdateProfile` hook
 - [x] Implement `useUpdateUserAvatar` hook
 - [x] Update user on `AsyncStorage`
