### ISSUE TITLE
TypeScript Improvements

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/gobarber-mobile#12]
## Description 
Improve type definitions for low maintainability 

## Tasks
- [x] Use Type Literals instead of Interfaces 
- [x]  Use consts instead of Enums 
- [x] Improve generic parameters names
