### ISSUE TITLE
Implement screen to create appointment

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/gobarber-mobile#5]
## Tasks

- [x] Implement Header component (Extract existing one from DashboardHeader)

### Providers List
- [x] Show the horizontal list of providers 
- [x] Selected the provider chosen on the previous screen 
- [x] Handle the selection of different providers

### Schedule 
- [x] Show date picker 
- [x] Initialize date picker with the current date
- [x] Disable dates that are unavailable 
- [x] Show hours available according to the selected date
- [x] Disable hours that are unavailable

Notes
- On Android, show a button to open the date picker (calendar). 
- On IOS, show the date picker directly, without needing to toggle it since it's not a calendar.

### UI Components

- [x] Implement Title 
![image](https://user-images.githubusercontent.com/48022589/105257336-570a0b80-5b66-11eb-8bb9-f0ab9ad3e7ad.png)

- [x] Implement horizontal list 
![image](https://user-images.githubusercontent.com/48022589/105257344-5d988300-5b66-11eb-9723-a8cc9fe4e7eb.png)
![image](https://user-images.githubusercontent.com/48022589/105257348-61c4a080-5b66-11eb-8bc4-89f89f3abe2c.png)

-  [x] Implement header
![image](https://user-images.githubusercontent.com/48022589/105257432-8587e680-5b66-11eb-820c-611dd39233d6.png)

![image](https://user-images.githubusercontent.com/48022589/105257443-90427b80-5b66-11eb-9ffb-d265aea542bc.png)

- [x] Implement date picker

### Appointment Types

- [x] Show an list with the available appointment types

### Create Appointment 

- [x] Implement `useCreateAppointment` hook
- [x] Send a `POST` request to create an appointment and pass the appointment date, provider id, and type
- [x] If success, redirect to a success screen (To be implemented in another PR, for now, just add the route and a base file)
- [x] Show an alert for errors

## Notes

Handle the loading state while loading the providers - Pay attention to avoid flickering
